// Regenerates src/core/wasm-bytes.js from wasm/parserTron2.wasm.
// Run after replacing the binary: bun scripts/embed-wasm.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const bytes = readFileSync(join(root, 'wasm', 'parserTron2.wasm'));
const out =
	'// GENERATED by scripts/embed-wasm.mjs — do not edit by hand.\n' +
	`// Source: wasm/parserTron2.wasm (${bytes.length} bytes).\n` +
	`export const WASM_BASE64 =\n\t'${bytes.toString('base64')}';\n`;
writeFileSync(join(root, 'src', 'core', 'wasm-bytes.js'), out);
console.log(`embedded ${bytes.length} bytes -> src/core/wasm-bytes.js`);
